# fly.toml app configuration file generated for catalogosocial on 2024-01-02T18:40:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "catalogosocial"
primary_region = "eze"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[[mounts]]
  source = "catalogosocial_data"
  destination = "/extvol"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[statics]]
  guest_path = "/extvol/media"
  url_prefix = "/media/"
