# Generated by Django 5.0 on 2023-12-18 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dcat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetExtras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_landing_page", models.URLField(blank=True, null=True)),
                ("original_id", models.CharField(blank=True, max_length=255)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="dcat.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionExtras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_access_url", models.URLField(blank=True, null=True)),
                ("original_download_url", models.URLField(blank=True, null=True)),
                ("original_id", models.CharField(blank=True, max_length=255)),
                (
                    "distribution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="dcat.distribution",
                    ),
                ),
            ],
        ),
    ]
