# Generated by Django 5.0 on 2024-01-06 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetextras",
            name="original_id",
        ),
        migrations.RemoveField(
            model_name="datasetextras",
            name="original_landing_page",
        ),
        migrations.RemoveField(
            model_name="distributionextras",
            name="original_access_url",
        ),
        migrations.RemoveField(
            model_name="distributionextras",
            name="original_download_url",
        ),
        migrations.RemoveField(
            model_name="distributionextras",
            name="original_id",
        ),
    ]
